name: L2
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build-L2:
    runs-on: ubuntu-latest
    


    steps:
      - name: Create SSH key pair
        run: |
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""

      - name: Clone repository
        run: |
          git clone https://github.com/Furius-Starfall/DevOps01.git

      - name: Create branch and do changes
        run: |
          cd DevOps01
          git config --global user.email "PetrH@gmail.com"
          git config --global user.name "Petr"
          git checkout -b BranchL2
          echo "Uprava z runneru" >> README.md
          git add README.md
          git commit -m "Editing README.md from GitHub Actions"
          pwd
          ls -la
        
      - name: push changes
        run: |
          git push BranchL2

      - name: merge branch
        run: |
          git checkout main
          git merge BranchL2
          git push origin main


#      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
#      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#      - name: Check out repository code
#        uses: actions/checkout@v4
#      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
#      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
#      - name: List files in the repository
#        run: |
#          ls ${{ github.workspace }}
#      - run: echo "🍏 This job's status is ${{ job.status }}."
