name: L2_1
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
permissions:
  contents: read
jobs:
  build-L2:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.5'
